services:
  extractor:
    build: ./extractor
    container_name: extractor-container
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace
    command: sleep infinity


  ollama:
    image: ollama/ollama:latest
    container_name: ollama-container
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  
