import logging
import requests
import json
from typing import Dict, List

from src.application.ports.queue_ports import AIServicePort
from src.infrastructure.ai.prompts import SUMMARIZE_SYSTEM_PROMPT
from app.core.config import settings

logger = logging.getLogger(__name__)


class AIAgent(AIServicePort):
    """AI Agent for text simplification and summarization using Ollama"""

    def __init__(self, ollama_host: str = settings.LLM_HOST):

        self.ollama_host = ollama_host
        self.endpoint = f"{ollama_host}/api/generate"
        self.model = settings.LLM_MODEL
        self.system_prompt = SUMMARIZE_SYSTEM_PROMPT

    def summarize_content(self, content: str) -> str:
        """
        Generate a summary of the provided content

        Args:
            content: Text to summarize (can include HTML)

        Returns:
            str: Summary generated by the AI
        """
        if not content or not content.strip():
            return ""

        # If content is very short, it doesn't need a summary
        if len(content.split()) < 20:
            return content

        payload = {
            "model": self.model,
            "system": self.system_prompt,
            "prompt": f"Summarize the following content concisely:\n\n{content}",
            "stream": False,
        }
        # TODO migrate to LangChain to have structured response with error handling, token counting, etc.
        try:
            response = requests.post(
                self.endpoint,
                json=payload,
                headers={"Content-Type": "application/json"},
                timeout=120,  # 2 minutes timeout
            )
            response.raise_for_status()

            result = response.json()
            summary = result.get("response", "")

            return summary.strip()

        except requests.exceptions.RequestException as e:
            logger.error("Error communicating with Ollama: %s", e)
            raise RuntimeError(f"Ollama unreachable: {e}") from e
        except json.JSONDecodeError as e:
            logger.error("Error decoding JSON response: %s", e)
            raise RuntimeError("Invalid response from Ollama") from e
        except Exception as e:
            logger.exception("Unexpected error during summarization")
            raise

    def summarize_batch(self, contents: List[str]) -> List[str]:
        """
        Generate summaries for multiple contents

        Args:
            contents: List of texts to summarize

        Returns:
            List[str]: List of generated summaries
        """
        summaries = []
        for i, content in enumerate(contents):
            logger.debug("Processing summary %d/%d", i + 1, len(contents))
            summary = self.summarize_content(content)
            summaries.append(summary)
        return summaries

    def test_connection(self) -> bool:
        """
        Test connection with Ollama server

        Returns:
            bool: True if connection is successful
        """
        try:
            response = requests.get(f"{self.ollama_host}/api/tags", timeout=5)
            response.raise_for_status()
            logger.info("Successful connection to Ollama")
            return True
        except Exception as e:
            logger.warning("Connection error with Ollama: %s", e)
            return False

    def get_connection_info(self) -> Dict[str, str]:
        return {"host": self.ollama_host, "model": self.model}


# Usage example
if __name__ == "__main__":
    agent = AIAgent()

    # Test connection
    if agent.test_connection():
        # Test summary with clean text (no HTML)
        test_content = """
        Google Cloud Storage is a service for storing your objects in Google Cloud. 
        You can use GCS for storing image, video, audio, and unstructured data. 
        You can combine these individual data types into large files of size at least 100 MB 
        and in between 100 to 10,000 shards to improve read and write throughput.
        """

        summary = agent.summarize_content(test_content)
        logger.info("Generated summary: %s", summary)
